#    Datatypes and Array operations

type mater 



In [22]:
import numpy as np

ex1 = np.array([11,12])

print(ex1.dtype)

int32


In [23]:
ex2 = np.array([11.0, 12.0])

print(ex2.dtype)

float64


In [24]:
ex3 = np.array([11,21], dtype = np.int64)
print(ex3.dtype)

int64


In [25]:
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)


int64

[11 12]


In [26]:
ex5 = np.array([11,21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


Arithmetic Array Operations

In [27]:
x = np.array([[111,112],[121,122]], dtype = np.int)
y = np.array([[211.1,212.1],[221.1,222.1]],dtype = np.float64)
print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [28]:
#add
print(x+y) #the plus sign works
print()
print(np.add(x,y))# so does the numpy function "add"



[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [29]:
#add
print(x-y) #the plus sign works
print()
print(np.subtract(x,y))# so does the numpy function "add"



[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [30]:
#add
print(x*y) #the plus sign works
print()
print(np.multiply(x,y))# so does the numpy function "add"



[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [31]:
#add
print(x/y) #the plus sign works
print()
print(np.divide(x,y))# so does the numpy function "add"



[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [32]:
#square root

print(np.sqrt(x))


[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [33]:
#expoente (e**x)

print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [34]:
# setup a random 2 x 4 matrix

arr = 10 + np.random.randn(2,5)
print(arr)

[[ 8.68532336  8.88198545 11.85076654 10.44045142  8.02549293]
 [ 9.30266737  9.79872091  9.72480004 11.14164881  9.91018505]]


In [35]:
# compute the mean for all elements

print(arr.mean())


9.776204188055562


In [36]:
#compute the means by colum

print(arr.mean(axis = 0))


[ 8.99399536  9.34035318 10.78778329 10.79105011  8.96783899]


In [37]:
# sum all the elements

print(arr.sum())


97.76204188055561


In [38]:
#compute the medians per witch row

print(np.median(arr,axis = 1)) #axis = eixo

[8.88198545 9.79872091]


# sorting


In [39]:
# create a 10 element array of randoms

unsorted = np.random.randn(10)

print(unsorted)

[-0.93223192 -0.01346724 -0.32156667  0.62622537 -0.22392406 -1.54392202
 -0.00444446  1.09093745 -0.12048562  0.29207235]


In [40]:
# create copy and sort

sorted = np.array(unsorted)
sorted.sort()

print(sorted)

print()

print(unsorted)


[-1.54392202 -0.93223192 -0.32156667 -0.22392406 -0.12048562 -0.01346724
 -0.00444446  0.29207235  0.62622537  1.09093745]

[-0.93223192 -0.01346724 -0.32156667  0.62622537 -0.22392406 -1.54392202
 -0.00444446  1.09093745 -0.12048562  0.29207235]


In [41]:
#inplace sorting

unsorted.sort()

print(unsorted)


[-1.54392202 -0.93223192 -0.32156667 -0.22392406 -0.12048562 -0.01346724
 -0.00444446  0.29207235  0.62622537  1.09093745]


# finding unique elements


In [42]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


# Set Operations with np.array data type:

In [44]:
s1 = np.array(['desk','chair','bulb'])

s2 = np.array(['lamp','bulb','chair'])

print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [51]:
print(s1,s2)
print(np.intersect1d(s1,s2))

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']
['bulb' 'chair']


In [52]:
print(s1,s2)
print(np.union1d(s1,s2))# junta elesmentos sem repetir os que sao iguais

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']


In [53]:
print(s1,s2)
print(np.setdiff1d(s1,s2)) # pega apenas elementos que tem em um e nao em outra lista

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']
['desk']


In [54]:
print(s1,s2)

print(np.in1d(s1,s2))# cada elemento que está em S1 e também em s2

#deks não está em s2 mas chair e bulb estão

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']
[False  True  True]
